services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: media-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_sharing
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - appnet

  # MinIO Object Storage
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5
    restart: unless-stopped
    networks:
      - appnet

  # MinIO Setup (create buckets)
  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/media-sharing;
      mc mb --ignore-existing myminio/frontend-assets;
      echo '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":"*","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::media-sharing/*"]}]}' > /tmp/media-sharing-policy.json;
      mc policy set-json /tmp/media-sharing-policy.json myminio/media-sharing;
      mc anonymous set download myminio/frontend-assets;
      mkdir -p /tmp/frontend/latest;
      echo '<html><body><h1>Frontend Placeholder</h1><p>This confirms MinIO access is working correctly.</p></body></html>' > /tmp/frontend/latest/index.html;
      mc cp /tmp/frontend/latest/index.html myminio/frontend-assets/latest/index.html;
      echo 'MinIO setup completed successfully';
      exit 0;
      "
    networks:
      - appnet

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: media-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: media_sharing

      # MinIO / S3 settings (belső elérés)
      BLOB_STORAGE_ENDPOINT: minio
      BLOB_STORAGE_PORT: 9000
      BLOB_STORAGE_USE_SSL: "false"
      BLOB_STORAGE_ACCESS_KEY: minioadmin
      BLOB_STORAGE_SECRET_KEY: minioadmin
      BLOB_STORAGE_BUCKET: media-sharing
      BLOB_STORAGE_REGION: eu-central-1
      BLOB_STORAGE_PUBLIC_URL: http://localhost:9000
      BLOB_STORAGE_INTERNAL_ENDPOINT: minio

      TRUSTED_ORIGINS: "*"
      ALLOWED_HEADERS: "*"
    depends_on:
      postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  # Frontend Nginx Proxy
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: media-frontend
    ports:
      - "80:80"
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_BUCKET: frontend-assets
      FRONTEND_VERSION: latest
      API_URL: http://backend:3000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - appnet

volumes:
  postgres_data:
  minio_data:

networks:
  appnet:
    driver: bridge
